version: '3'

services:
  takenote-v3_db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - takenotedata:/var/lib/postgresql/data
    networks:
      - app-connect
  takenote-v3_api:
    image: api
    restart: always
    build:
      context: ./takenote-v3_api
    depends_on: 
      - takenote-v3_db
    ports:
      - 3000:3000
    networks:
      - app-connect
    command: bash -c "npm run dev"
    volumes:
      - ./takenote-v3_api/src:/takenote/src
networks:
  app-connect:
    driver: bridge
volumes:
  takenotedata: